[package]
name = "hh_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
thirtyfour = "0.36.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3.31"

[[bin]]
name = "hh_bot"
path = "src/main.rs"